import Foundation
import WeiBeiCore

/**
 * 验证 WorkspaceStore、课程空间和跨界面命令契约。
 */
enum WorkspaceStoreSelfChecks {
    /**
     * 执行该领域的自检。
     */
    @MainActor
    static func run(repositoryURL: URL) throws {
        let workspaceStoreSource = SelfCheckSupport.source("Sources/WeiBei/Stores/WorkspaceStore.swift", repositoryURL: repositoryURL)
        let appSource = SelfCheckSupport.source("Sources/WeiBei/App/WeiBeiApp.swift", repositoryURL: repositoryURL)
        let contentViewSource = SelfCheckSupport.source("Sources/WeiBei/Views/ContentView.swift", repositoryURL: repositoryURL)
        let sidebarSource = SelfCheckSupport.source("Sources/WeiBei/Views/SidebarView.swift", repositoryURL: repositoryURL)
        let commandPaletteSource = SelfCheckSupport.source("Sources/WeiBei/Views/CommandPaletteView.swift", repositoryURL: repositoryURL)
        let notesAgentSource = SelfCheckSupport.source("Sources/WeiBei/Views/NotesAgentView.swift", repositoryURL: repositoryURL)
        let readerViewSource = SelfCheckSupport.source("Sources/WeiBei/Views/ReaderView.swift", repositoryURL: repositoryURL)
        let agentSettingsSource = appSource + "\n" + SelfCheckSupport.joinedSources(
            in: "Sources/WeiBei/Views/Settings",
            pathExtension: "swift",
            repositoryURL: repositoryURL
        )

        let interactiveInputSources = [contentViewSource, sidebarSource, commandPaletteSource, notesAgentSource, appSource].joined(separator: "\n")
        expect(!interactiveInputSources.contains(".weibeiInputPrompt("), "interactive input placeholders stay on native prompts instead of overlay text")
        expect(agentSettingsSource.contains("WeiBeiTextActionButtonStyle(active: true)") && agentSettingsSource.contains(".background(WeiBeiTheme.paper)") && agentSettingsSource.contains("WeiBeiGlassHeaderBackground(paperOpacity: 0.66"), "settings view uses WeiBei paper, glass header, and button styles")
        expect(appSource.contains("init() {")
            && appSource.contains("WeiBeiTypography.registerBundledFonts()"), "app registers bundled WeiBei fonts before the SwiftUI window tree is built")
        expect(workspaceStoreSource.components(separatedBy: "recordVerificationStage(\"completed\")").count >= 4, "verification scenarios record completion before capture")
        let linkedSourcesSourceURL = repositoryURL
            .appendingPathComponent("Sources/WeiBei/Views/LinkedSourcesView.swift")
        let linkedSourcesSource = (try? String(contentsOf: linkedSourcesSourceURL, encoding: .utf8)) ?? ""
        let courseWorkspaceSourceNames = [
            "CourseWorkspaceView.swift",
            "CourseHubView.swift",
            "CourseRelationsView.swift",
            "CourseRelationPaperView.swift",
            "CourseRelationGraphModel.swift",
            "CourseImmersiveDrawerView.swift",
            "CourseRecordsView.swift",
            "CourseWorkspaceComponents.swift",
        ]
        let courseWorkspaceSource = courseWorkspaceSourceNames.map { name in
            let url = repositoryURL
                .appendingPathComponent("Sources/WeiBei/Views")
                .appendingPathComponent(name)
            return (try? String(contentsOf: url, encoding: .utf8)) ?? ""
        }.joined(separator: "\n")
        let selectItemSource: String = {
            guard let start = workspaceStoreSource.range(of: "func select(itemID: String?)")?.lowerBound,
                  let end = workspaceStoreSource[start...].range(of: "func selectAdjacentItem")?.lowerBound else {
                return ""
            }
            return String(workspaceStoreSource[start..<end])
        }()
        expect(!selectItemSource.contains("activeNotebookItemID = nil")
            && selectItemSource.contains("selectedItemID = itemID"), "opening another material does not detach the note the user is writing")
        expect(workspaceStoreSource.contains("noteSourceLinksMigrationVersion < 1")
            && workspaceStoreSource.contains("noteSourceLinksMigrationVersion = 1")
            && workspaceStoreSource.contains("setLinkedSourceIDsForActiveNote"), "note-source migration runs once and explicit relationship management remains available")
        expect(workspaceStoreSource.contains("invalidateAgentContext()\n            activeNotebookItemID = item.id")
            && workspaceStoreSource.components(separatedBy: "removeLinksWhereSourceItemID").count >= 3, "switching notes invalidates in-flight agent work and source-to-note conversion removes invalid relationships")
        expect(linkedSourcesSource.contains("@State private var noteItemID: String?")
            && linkedSourcesSource.contains("noteItemID = store.activeNotebookItemID")
            && linkedSourcesSource.contains("store.setLinkedSourceIDs(draftIDs, for: noteItemID)"), "relationship editing remains bound to the note that opened the popover")
        expect(contentViewSource.contains("if store.courseWorkspacePresented")
            && contentViewSource.contains("CourseWorkspaceView()")
            && contentViewSource.contains("LayoutContentView()")
            && contentViewSource.contains("container.isHidden = store.courseWorkspacePresented")
            && !contentViewSource.contains("if store.courseWorkspacePresented {\n                            CourseWorkspaceView()\n                        } else"), "course workspace covers and hides native pane hosts without replacing the persistent pane tree")
        expect(courseWorkspaceSource.contains("case hub")
            && courseWorkspaceSource.contains("case relations")
            && courseWorkspaceSource.contains("case records")
            && !courseWorkspaceSource.contains("case overview")
            && courseWorkspaceSource.contains("CourseHubView(")
            && courseWorkspaceSource.contains("对话记录")
            && courseWorkspaceSource.contains("管理关系")
            && courseWorkspaceSource.contains("导入文稿")
            && courseWorkspaceSource.contains("导入笔记")
            && courseWorkspaceSource.contains("CourseHubRowProminence")
            && courseWorkspaceSource.contains("选择一门课程")
            && courseWorkspaceSource.contains("选择课程")
            && courseWorkspaceSource.contains("关系台")
            && courseWorkspaceSource.contains("资料与笔记")
            && courseWorkspaceSource.contains("资料关系台")
            && courseWorkspaceSource.contains("同色标签表示同一课程")
            && courseWorkspaceSource.contains("primaryCourseID(for:")
            && courseWorkspaceSource.contains("CourseHubColumnEmptyState")
            && courseWorkspaceSource.contains("courseTitleDisplayFont")
            && courseWorkspaceSource.contains("frame(height: 44, alignment: .center)")
            && courseWorkspaceSource.contains("继续阅读")
            && courseWorkspaceSource.contains("继续对话")
            && courseWorkspaceSource.contains("CourseHubContinueRow")
            && courseWorkspaceSource.contains("linkedSessionIDs"), "course workspace hub is a continue-learning launcher with course picking and material-linked conversation prominence")
        expect(courseWorkspaceSource.contains("CourseRelationPaperView(")
            && courseWorkspaceSource.contains("CourseImmersiveDrawerView")
            && (courseWorkspaceSource.contains("static let width: CGFloat = 292")
                || courseWorkspaceSource.contains(".frame(width: 292)")
                || courseWorkspaceSource.contains("CourseDrawerContainerView.panelWidth"))
            && courseWorkspaceSource.contains("未归属课程")
            && courseWorkspaceSource.contains("未建立关系")
            && courseWorkspaceSource.contains("showsOnlyUnlinked")
            && courseWorkspaceSource.contains("edgeHazeColor")
            && courseWorkspaceSource.contains("nodeProminence")
            && courseWorkspaceSource.contains("private struct CourseRelationPaperNodeView: View"), "course drawer and relation paper share explicit course membership while keeping course assignment separate from note-material links")
        expect(courseWorkspaceSource.contains("@State private var pendingConnection")
            && courseWorkspaceSource.contains("private func handleConnectionTap")
            && courseWorkspaceSource.contains("private func connectionButton")
            && courseWorkspaceSource.contains("MagnificationGesture()")
            && courseWorkspaceSource.contains("private func zoomControls")
            && courseWorkspaceSource.contains("private func fitZoomScale")
            && courseWorkspaceSource.contains("scrollProxy.scrollTo(Self.paperOriginID, anchor: .topLeading)")
            && courseWorkspaceSource.contains("private struct CourseRelationNodeDragModifier")
            && courseWorkspaceSource.contains(".accessibilityLabel(\"\\(node.item.title)：\\(connectionLabel(state))\")")
            && courseWorkspaceSource.contains("private static func fanOffsets")
            && courseWorkspaceSource.contains("courseScopeRail")
            && courseWorkspaceSource.contains("private var defaultScope")
            && courseWorkspaceSource.contains("let candidate = scope ?? defaultScope")
            && courseWorkspaceSource.contains("Thin toolbar only")
            && courseWorkspaceSource.contains("frame(height: 40)"), "relationship paper scopes by course on a left rail, defaults to the active course, uses a thin toolbar, supports click-to-link and zoom, and fans dense bands at shared nodes")
        expect(courseWorkspaceSource.contains("更改自动保存")
            && courseWorkspaceSource.contains("private func addLink(materialID: String, noteID: String)")
            && courseWorkspaceSource.contains("private func removeLink(noteID: String, materialID: String)")
            && courseWorkspaceSource.contains("store.setLinkedNoteIDs")
            && courseWorkspaceSource.contains("store.setLinkedCourseSourceIDs")
            && !courseWorkspaceSource.contains("store.courseMaterials + store.sampleItems"), "course relationship edits save immediately in both directions while built-in samples stay outside course counts")
        expect(workspaceStoreSource.contains("@Published private(set) var workspaceSaveError")
            && workspaceStoreSource.contains("func retryWorkspaceSave()")
            && workspaceStoreSource.contains("Course changes were not saved to disk")
            && courseWorkspaceSource.contains("保存失败，点此重试")
            && courseWorkspaceSource.contains("draft.automaticMaterialCount + draft.markdownFiles.count - notePaths.count")
            && courseWorkspaceSource.contains("url.deletingLastPathComponent().path"), "course autosave failures stay visible and mixed-folder classification reports complete counts with unambiguous paths")
        expect(workspaceStoreSource.contains("func presentCourseWorkspace(")
            && workspaceStoreSource.contains("CourseWorkspaceDestination = .hub")
            && workspaceStoreSource.contains("func openCourseSpace(_ courseID: UUID)")
            && workspaceStoreSource.contains("func sessionsTouchingCourse(_ courseID: UUID)")
            && workspaceStoreSource.contains("func sessionsTouchingMaterial(_ materialID: String")
            && workspaceStoreSource.contains("func primaryCourseID(for session: StudySession)")
            && workspaceStoreSource.contains("func importCourseFilesFromURLs(_ urls: [URL]")
            && workspaceStoreSource.contains("func dismissCourseWorkspace()")
            && workspaceStoreSource.contains("func openCourseMaterial(")
            && workspaceStoreSource.contains("func openCourseNote(")
            && workspaceStoreSource.contains("func continueCourseSession(")
            && workspaceStoreSource.contains("func prepareCourseFolderImportFromPanel()")
            && workspaceStoreSource.contains("func importCourseMaterialsFromPanel()")
            && workspaceStoreSource.contains("func importCourseNotesFromPanel()")
            && workspaceStoreSource.contains("markdownNotePaths: Set<String>? = nil")
            && workspaceStoreSource.contains("reclassifiesExistingMarkdown: true")
            && workspaceStoreSource.contains("defaultMarkdownIsNotebookNote")
            && workspaceStoreSource.contains("func createCourseNotebookNote(title: String) -> String?")
            && courseWorkspaceSource.contains("确认 Markdown 的角色")
            && courseWorkspaceSource.contains("guard let noteID = store.createCourseNotebookNote")
            && courseWorkspaceSource.contains("newNoteError = store.noteFileError")
            && courseWorkspaceSource.contains("store.sessionsTouchingCourse(courseID)")
            && courseWorkspaceSource.contains("importCourseFilesFromURLs")
            && appSource.contains("打开课程空间")
            && commandPaletteSource.contains("打开课程空间")
            && sidebarSource.contains("store.presentCourseWorkspace(.hub)")
            && linkedSourcesSource.contains("store.presentCourseWorkspace(.notes"), "course hub routing, session membership helpers, and top-level open actions stay wired without replacing note-relationship entry points")
        expect(workspaceStoreSource.contains("scenario == \"course-index-navigation-flow\"")
            && workspaceStoreSource.contains("course-material-unassigned")
            && workspaceStoreSource.contains("activeCourseID = nil")
            && workspaceStoreSource.contains("showLibrary = true")
            && workspaceStoreSource.contains("CourseItemMemberships()"), "course-drawer verification uses isolated real courses, shared items, and one genuinely unassigned material")
        expect(workspaceStoreSource.contains("noteSourceRelationIndex = NoteSourceRelationIndex(links: noteSourceLinks)")
            && workspaceStoreSource.contains("func linkedNoteCount(for sourceItemID: String)")
            && workspaceStoreSource.contains("verifyCourseOverlayContinuity(itemID:")
            && workspaceStoreSource.contains("verifyCourseOverlayContinuity(itemID: \"sample-pdf\")")
            && workspaceStoreSource.contains("PaneToggleContinuityVerifier.endMeasurement()"), "course relationships use a reusable index and overlay continuity measures live HTML and PDF panes")
        expect(readerViewSource.contains("var isEnabled = true")
            && readerViewSource.contains("NSApp.modalWindow == nil")
            && courseWorkspaceSource.contains("isEnabled: !showsNewNotePrompt && store.courseFolderImportDraft == nil"), "escape dismisses only the active course surface and leaves sheets or file panels in control")
        expect(workspaceStoreSource.contains("DocumentTextExtractor.cachedText(for: item)")
            && workspaceStoreSource.contains("Task.detached(priority: .userInitiated)")
            && workspaceStoreSource.contains("DocumentTextExtractor.indexText(for: candidate.item, query: query)")
            && workspaceStoreSource.contains("DocumentTextExtractor.text(for: item)")
            && workspaceStoreSource.contains("candidate.item.id == currentMaterialID")
            && !workspaceStoreSource.contains("if let text = DocumentTextExtractor.text(for: item)"), "main-actor workspace reads cached document text; cold current-material extract runs inside the detached course-context task")
        expect(workspaceStoreSource.contains("@Published var showDailyInspiration = true")
            && workspaceStoreSource.contains("func setDailyInspirationEnabled(_ enabled: Bool)")
            && workspaceStoreSource.contains("showDailyInspiration = snapshot.showDailyInspiration ?? true")
            && workspaceStoreSource.contains("showDailyInspiration: showDailyInspiration"), "daily inspiration preference persists in the isolated workspace file and older workspaces default to enabled")
        expect(workspaceStoreSource.contains("var brandLatinName: String")
            && workspaceStoreSource.contains("\"WeiBei\"")
            && !contentViewSource.contains("Text(store.brandLatinName)")
            && !contentViewSource.contains("WeiBeiTypography.englishBrandFont(size: 15.5, weight: .semibold)")
            && !contentViewSource.contains("WeiBeiBrandMark.image(for: store.appearanceMode)")
            // Settings sidebar keeps a single localized title only — no second "WeiBei SETTINGS" line.
            && !agentSettingsSource.contains("Text(\"SETTINGS\")")
            && notesAgentSource.contains("latinMark: store.interfaceLanguage == .chinese ? \"NOTES\" : nil")
            && notesAgentSource.contains("latinMark: store.interfaceLanguage == .chinese ? \"CHAT\" : nil"), "top bar stays brandless; pane headers keep CHAT/NOTES marks; settings title is not duplicated")
        expect(notesAgentSource.contains("ForEach(NoteRenderMode.visibleCases)")
            && notesAgentSource.contains("switch store.noteRenderMode.visibleMode")
            && !notesAgentSource.contains("ForEach(NoteRenderMode.allCases)")
            && notesAgentSource.contains("let label = mode.label(language: store.interfaceLanguage)")
            && notesAgentSource.contains("Text(label)")
            && !notesAgentSource.contains("return \"Diff\"")
            && !notesAgentSource.contains("return \"Src\"")
            && !notesAgentSource.contains("private func compactModeLabel")
            && !notesAgentSource.contains("Text(\"预览\")")
            && !notesAgentSource.contains("Text(\"Preview\")")
            && notesAgentSource.contains(".accessibilityLabel(Text(label))")
            && notesAgentSource.contains(".help(label)"), "note pane header exposes only writing, compare, and source with clear shared labels and full accessibility/help text")
        expect(
            workspaceStoreSource.contains("shortcutKey(from event: NSEvent)")
                && workspaceStoreSource.contains("case 0: return \"a\"")
                && workspaceStoreSource.contains("case 18: return \"1\"")
                && workspaceStoreSource.contains("case 30: return \"]\"")
                && workspaceStoreSource.contains("case 33: return \"[\"")
                && workspaceStoreSource.contains("case 125: return \"down\""),
            "app shortcuts normalize hardware keys"
        )
        expect(workspaceStoreSource.contains("animateLayoutChange") && workspaceStoreSource.contains("withAnimation(WeiBeiMotion.layout)"), "app shortcut layout changes stay animated")
        expect(workspaceStoreSource.contains("animatePanelChange") && workspaceStoreSource.contains("withAnimation(WeiBeiMotion.panel)"), "app shortcut panel changes stay animated")
        expect(workspaceStoreSource.contains("if modifiers == [.command, .shift]") && workspaceStoreSource.contains("applyLastAgentAnswerToNote()") && workspaceStoreSource.contains("replaceSelectionWithLastAgentAnswer()") && workspaceStoreSource.contains("applyAgentPatchToEditor()"), "app shortcut handler owns command-shift agent write actions")
        expect(workspaceStoreSource.contains("case \"a\":\n                guard canApplyAgentAnswer else { return false }\n                animatePanelChange { applyLastAgentAnswerToNote() }")
            && workspaceStoreSource.contains("case \"r\":\n                guard canReplaceNoteSelection else { return false }\n                animatePanelChange { replaceSelectionWithLastAgentAnswer() }")
            && workspaceStoreSource.contains("case \"e\":\n                guard canApplyAgentAnswer else { return false }\n                animatePanelChange { applyAgentPatchToEditor() }"), "agent write shortcuts do not swallow unavailable actions")
        expect(workspaceStoreSource.contains("case \"j\":\n                guard layout.hasCollapsibleRightPane else { return false }\n                animateLayoutChange { toggleRightPane() }"), "right-pane shortcut does not swallow unavailable layouts")
        expect(workspaceStoreSource.contains("case \"2\":\n                animateLayoutChange { setLayout(.documentNotesSplit) }")
            && !workspaceStoreSource.contains("case \"3\":\n                animateLayoutChange { setLayout(.documentNotesSplit) }")
            && workspaceStoreSource.contains("case \"s\":\n                guard layout.isDocumentThreePane else { return false }\n                animateLayoutChange { swapThreePaneSecondaryPanes() }"), "three-pane keyboard shortcuts match the command palette and only swap panes inside the three-pane workspace")
        expect(workspaceStoreSource.contains("case .navigateBack:")
            && workspaceStoreSource.contains("guard canNavigateBack else { return false }")
            && workspaceStoreSource.contains("animateLayoutChange { navigateBackInWorkspace() }")
            && workspaceStoreSource.contains("case .navigateForward:")
            && workspaceStoreSource.contains("guard canNavigateForward else { return false }")
            && workspaceStoreSource.contains("animateLayoutChange { navigateForwardInWorkspace() }")
            && workspaceStoreSource.contains("AppShortcutCatalog.action(matching:")
            && workspaceStoreSource.contains("performCustomizableShortcut"), "command-bracket shortcuts drive workspace back and forward via the customizable shortcut catalog")
        expect(workspaceStoreSource.contains("var canCopyReference: Bool")
            && workspaceStoreSource.contains("var copyReferenceActionTitle: String")
            && workspaceStoreSource.contains("hasSelectionAttachments || selectionContext != nil")
            && workspaceStoreSource.contains("if hasSelectionAttachments || selectionContext != nil { return ui(\"复制选区引用\"")
            && workspaceStoreSource.contains("if hasSelectedMaterial { return ui(\"复制资料引用\"")
            && workspaceStoreSource.contains("guard canCopyReference else { return false }")
            && workspaceStoreSource.contains("guard hasSelectedMaterial else { return false }"), "app shortcuts and menus name copy-reference by the actual current target")
        expect(workspaceStoreSource.contains("selectAdjacentItem(step: -1)")
            && workspaceStoreSource.contains("if isAskingAgent {\n                    cancelAgentRequest()")
            && workspaceStoreSource.contains("guard !agentDraft.trimmingCharacters")
            && workspaceStoreSource.contains("askAgent()"), "app shortcut handler covers navigation plus agent send and stop")
        expect(workspaceStoreSource.contains("return allItems.filter { itemMatchesLibrarySearch($0, query: query) }")
            && workspaceStoreSource.contains("return materialItems.filter { itemMatchesLibrarySearch($0, query: query) }")
            && workspaceStoreSource.contains("func displayTags(for item: StudyItem, limit: Int = 3) -> [String]")
            && workspaceStoreSource.contains("return Array(MarkdownTagSearch.tags(in: noteMarkdownText(for: item)).prefix(limit))")
            && workspaceStoreSource.contains("private func noteTagsMatchLibrarySearch(_ item: StudyItem, query: String) -> Bool")
            && workspaceStoreSource.contains("private func noteMarkdownText(for item: StudyItem) -> String")
            && workspaceStoreSource.contains("MarkdownTagSearch.matches(query: query, in: noteMarkdownText(for: item))")
            && workspaceStoreSource.contains("item.id == activeNoteItemID"), "course index search includes active and cached notebook Markdown tags without indexing all notes separately")
        expect(workspaceStoreSource.contains("backNavigationStack: [NavigationSnapshot]")
            && workspaceStoreSource.contains("forwardNavigationStack: [NavigationSnapshot]")
            && workspaceStoreSource.contains("func navigateBackInWorkspace()")
            && workspaceStoreSource.contains("func navigateForwardInWorkspace()")
            && workspaceStoreSource.contains("private func recordNavigationPoint()")
            && workspaceStoreSource.contains("private func applyNavigationSnapshot")
            && workspaceStoreSource.contains("forwardNavigationStack.append(navigationSnapshot())")
            && workspaceStoreSource.contains("backNavigationStack.append(navigationSnapshot())")
            && workspaceStoreSource.contains("agentSurface == .selectionFloat ? .hidden : agentSurface"), "workspace back/forward stores app page state without restoring transient selection floats")
        expect(workspaceStoreSource.contains("@Published var readerPageIndex = 0")
            && workspaceStoreSource.contains("var readerPageIndex: Int")
            && workspaceStoreSource.contains("func updateReaderPageIndex(_ index: Int)")
            && workspaceStoreSource.contains("func recordReaderPageNavigationPoint()")
            && workspaceStoreSource.contains("readerPageIndex: readerPageIndex")
            && workspaceStoreSource.contains("selectedMaterialItem?.kind == .pdf ? snapshot.readerPageIndex : nil")
            && workspaceStoreSource.contains("recordsLocation: false"), "workspace navigation snapshots restore PDF page position without treating restoration as new study activity")
        expect(workspaceStoreSource.contains("case \"return\":\n                if isAskingAgent")
            && workspaceStoreSource.contains("guard !agentDraft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty else { return false }"), "app shortcut stops a running answer but does not swallow command-return when idle with no draft")
        expect(workspaceStoreSource.contains("showQuietInsight = false")
            && !workspaceStoreSource.contains("agentSurface == .quietInsight")
            && !workspaceStoreSource.contains("setAgentSurface(.quietInsight)"), "quiet insight surface is disabled and no longer auto-enabled on immersive reading")
        expect(workspaceStoreSource.contains("@Published var activeNotebookItemID")
            && workspaceStoreSource.contains("var activeNoteItem: StudyItem?")
            && workspaceStoreSource.contains("guard itemID == activeNoteItemID else { return }"), "note writes are bound to the active note instead of the selected reader material")
        expect(workspaceStoreSource.contains("private var pendingNotePersistenceByItemID: [String: PendingNotePersistence] = [:]")
            && workspaceStoreSource.contains("private var pendingNotePersistenceTasks: [String: Task<Void, Never>] = [:]")
            && workspaceStoreSource.contains("private let notePersistenceDebounceDelay")
            && workspaceStoreSource.contains("func updateNote(_ value: String) {\n        guard noteText != value else { return }")
            && workspaceStoreSource.contains("scheduleNotePersistence(value, for: item)")
            && !workspaceStoreSource.contains("func updateNote(_ value: String) {\n        noteText = value\n        clearGeneratedQuietInsight()\n        persistCurrentNote()\n        save()")
            && workspaceStoreSource.contains("func flushPendingNotePersistence()")
            && appSource.contains("sharedWorkspaceStore.flushPendingNotePersistence()"), "markdown typing updates memory immediately but debounces note persistence and flushes pending edits on quit")
        expect(workspaceStoreSource.contains("let item = allItems.first(where: { $0.id == itemID && $0.isNotebookNote })")
            && workspaceStoreSource.contains("activeNotebookItemID = item.id")
            && workspaceStoreSource.contains("noteText = noteText(for: item)")
            && !workspaceStoreSource.contains("select(itemID: item.id)\n            noteFileError = ui(\"已创建笔记"), "selecting or creating a notebook note does not replace the current reader material")
        expect(workspaceStoreSource.contains("@Published var readerLocationID")
            && workspaceStoreSource.contains("@Published var readerLocationTitle")
            && workspaceStoreSource.contains("func updateReaderHTMLLocation")
            && workspaceStoreSource.contains("var currentReferenceTitle"), "store tracks durable PDF and HTML reader locations")
        expect(workspaceStoreSource.contains("private func sessionContinuitySummary(for session: StudySession)")
            && workspaceStoreSource.contains("messages.suffix(20)")
            && workspaceStoreSource.contains("olderMessages.prefix(4)")
            && workspaceStoreSource.contains("olderMessages.suffix(8)"), "durable study sessions inject recent turns plus bounded earlier conversation excerpts into each clean PI run")
        expect(workspaceStoreSource.contains("let itemTitle = sourceReferenceBaseTitle(for: item)")
            && workspaceStoreSource.contains("itemTitle: itemTitle")
            && workspaceStoreSource.contains("private func refreshStudyLocationReferenceTitles() -> Bool")
            && workspaceStoreSource.contains("learningMemoryEntries[index].origin = .userStatement\n                    learningMemoryEntries[index].sessionID = activeStudySessionID")
            && workspaceStoreSource.contains("$0.sessionID == activeStudySessionID")
            && workspaceStoreSource.contains("learningMemoryEntries[index].origin == .userStatement")
            && workspaceStoreSource.contains("proposed.origin != .userStatement")
            && !workspaceStoreSource.contains("learningMemoryEntries[index].sessionID = activeStudySessionID\n                learningMemoryEntries[index].updatedAt"), "learning locations preserve duplicate-file identity and inferred memories keep their original session provenance")
        expect(workspaceStoreSource.contains("@Published var readerTargetPageIndex")
            && workspaceStoreSource.contains("@Published var readerTargetLocationTitle")
            && workspaceStoreSource.contains("func openSourceReference")
            && workspaceStoreSource.contains("reference.sectionTitle")
            && workspaceStoreSource.contains("reference.sectionLocationID")
            && workspaceStoreSource.contains("reference.sectionOrdinal.map { \"html-heading-\\(max($0 - 1, 0))\" }")
            && workspaceStoreSource.contains("private func sourceReferenceBaseTitle")
            && workspaceStoreSource.contains("return matches.count == 1 ? matches[0] : nil"), "store can jump from source references to PDF pages and HTML sections without guessing between duplicate file titles")
        expect(workspaceStoreSource.contains("let sampleItems: [StudyItem] = WorkspaceStore.makeSampleItems()")
            && workspaceStoreSource.contains("StudyItem(id: \"sample-pdf\", title: \"Mishkin 教材样例\", subtitle: \"PDF 阅读\", kind: .pdf, urlPath: samplePDFURL()?.path, isSample: true)")
            && workspaceStoreSource.contains("private var didRunVerificationScenario = false")
            && workspaceStoreSource.contains("func runVerificationScenarioIfNeeded() async")
            && workspaceStoreSource.contains("let scenario = Self.environmentValue(\"WEIBEI_VERIFY_SCENARIO\")")
            && workspaceStoreSource.contains("scenario == \"offline-learning-flow\"")
            && workspaceStoreSource.contains("scenario == \"immersive-conversation-flow\"")
            && workspaceStoreSource.contains("scenario == \"notebook-creation-flow\"")
            && workspaceStoreSource.contains("layout = scenario == \"immersive-conversation-flow\" ? .immersiveConversation : .documentAgentNotes")
            && workspaceStoreSource.contains("if scenario == \"notebook-creation-flow\" {\n            layout = .immersiveWriting")
            && workspaceStoreSource.contains("showLibrary = scenario != \"immersive-conversation-flow\"")
            && workspaceStoreSource.contains("updateSelection(\n            ui(\"利率是资金使用价格的表达。\"")
            && workspaceStoreSource.contains("await askAgentAndWait()")
            && workspaceStoreSource.contains("applyLastAgentAnswerToNote()")
            && workspaceStoreSource.contains("WEIBEI_FORCE_OFFLINE_AGENT")
            && workspaceStoreSource.contains("private static func workspaceRootDirectory() -> URL?")
            && workspaceStoreSource.contains("environmentValue(\"WEIBEI_WORKSPACE_DIR\")")
            && workspaceStoreSource.contains("let directory = root.appendingPathComponent(\"Samples\", isDirectory: true)")
            && workspaceStoreSource.contains("let directory = root.appendingPathComponent(\"Files\", isDirectory: true)")
            && workspaceStoreSource.contains("private static func writeSamplePDF(to url: URL) -> Bool")
            && workspaceStoreSource.contains("CGDataConsumer(data: data as CFMutableData)")
            && workspaceStoreSource.contains("利率是资金使用价格的表达。")
            && !workspaceStoreSource.contains("StudyItem(id: \"sample-pdf\", title: \"Mishkin 教材样例\", subtitle: \"PDF 阅读\", kind: .pdf, urlPath: nil, isSample: true)"), "sample PDF item points at a generated selectable PDF file instead of the fake PDF fallback")
        expect(workspaceStoreSource.contains("empty-workspace-light-wide")
            && workspaceStoreSource.contains("empty-workspace-light-narrow")
            && workspaceStoreSource.contains("empty-workspace-calligraphy-light")
            && workspaceStoreSource.contains("empty-workspace-calligraphy-dark")
            && workspaceStoreSource.contains("empty-workspace-dark-wide")
            && workspaceStoreSource.contains("empty-workspace-dark-narrow")
            && workspaceStoreSource.contains("empty-workspace-inspiration-off")
            && workspaceStoreSource.contains("configureEmptyWorkspaceVerificationScenario")
            && workspaceStoreSource.contains("guard Self.environmentValue(\"WEIBEI_SUPPRESS_ACTIVATION\") == \"1\" else { return }")
            && workspaceStoreSource.contains("showReader = false")
            && workspaceStoreSource.contains("showAgent = false")
            && workspaceStoreSource.contains("showNotes = false")
            && workspaceStoreSource.contains("case \"empty-workspace-open-doc\":\n            toggleReader()")
            && workspaceStoreSource.contains("case \"empty-workspace-open-chat\":\n            toggleAgent()")
            && workspaceStoreSource.contains("case \"empty-workspace-open-notes\":\n            toggleNotes()")
            && workspaceStoreSource.contains("Empty workspace entry state marker"), "verification scenarios cover empty light and dark wide and narrow windows plus all three preserved-state entry paths")
        expect(workspaceStoreSource.contains("ownerTitle: String? = nil") && workspaceStoreSource.contains("let resolvedOwnerTitle"), "selection updates can carry a precise reader source title")
        expect(workspaceStoreSource.contains("@Published var selectionAttachments: [SelectionContext] = []")
            && workspaceStoreSource.contains("@Published var floatingSelectionPrompt = \"\"")
            && workspaceStoreSource.contains("floatingSelectionPrompt = ui(\"当前选区\", \"Current selection\")")
            && workspaceStoreSource.contains("var agentSelectionTitle: String?")
            && workspaceStoreSource.contains("var agentSelectionText: String?")
            && workspaceStoreSource.contains("func removeSelectionAttachment(id: UUID)")
            && workspaceStoreSource.contains("if selectionContext?.id == id {\n                clearUnpinnedFloatingSelection(keepContext: false)")
            && workspaceStoreSource.contains("func clearSelectionAttachments()")
            && workspaceStoreSource.contains("private var pendingSelectionAttachmentTask: Task<Void, Never>?")
            && workspaceStoreSource.contains("private var lastSelectionUpdateDate: Date?")
            && workspaceStoreSource.contains("lastSelectionUpdateDate = Date()")
            && workspaceStoreSource.contains("now.timeIntervalSince($0) > selectionAttachmentMergeWindow")
            && !workspaceStoreSource.contains("guard Self.hasMeaningfulSelectionCharacter(cleaned) else {\n            lastSelectionUpdateDate = nil")
            && !workspaceStoreSource.contains("scheduleSelectionAttachment(nextSelection")
            && workspaceStoreSource.contains("private func scheduleSelectionAttachment(_ selection: SelectionContext, withinSelectionGesture: Bool)")
            && workspaceStoreSource.contains("private let selectionAttachmentDebounceDelay: UInt64 = 520_000_000")
            && workspaceStoreSource.contains("try? await Task.sleep(nanoseconds: self?.selectionAttachmentDebounceDelay ?? 520_000_000)")
            && workspaceStoreSource.contains("private func cancelPendingSelectionAttachment()")
            && workspaceStoreSource.contains("clearUnpinnedFloatingSelection(keepContext: false)")
            // Clear fragments lives on the conversation surface (NotesAgent), not Settings.
            && notesAgentSource.contains("store.clearSelectionAttachments()")
            && workspaceStoreSource.contains("func addSelectionAttachment(_ selection: SelectionContext, withinSelectionGesture: Bool = false)")
            && workspaceStoreSource.contains("private var lastSelectionAttachmentDate: Date?")
            && workspaceStoreSource.contains("private let selectionAttachmentMergeWindow: TimeInterval = 1.8")
            && workspaceStoreSource.contains("while let mergeIndex = selectionAttachments.indices.reversed().first")
            && workspaceStoreSource.contains("selectionAttachments.remove(at: mergeIndex)")
            && workspaceStoreSource.contains("SelectionAttachmentMerge.mergedText")
            && workspaceStoreSource.contains("withinSelectionGesture || withinSelectionGestureHint")
            && workspaceStoreSource.contains("let maxAttachments = 8")
            && workspaceStoreSource.contains("Live selection (before/without")
            && workspaceStoreSource.contains("if selectionAttachments.isEmpty,\n           let selectionContext,"), "agent selection context uses removable attachments, falls back to live selection, and attaches before send")
        expect(workspaceStoreSource.contains("selectionTitle: sentSelectionTitle")
            && workspaceStoreSource.contains("selectionText: sentSelectionText")
            && !workspaceStoreSource.contains("selectionText: selectionContext?.text,\n                recentMessages: recentMessages"), "agent requests capture selection via sentSelectionText (attachments or live fallback), not a raw live-only field")
        expect(workspaceStoreSource.contains("let sentSelectionTitle = agentSelectionTitle")
            && workspaceStoreSource.contains("let sentSelectionText = agentSelectionText")
            && workspaceStoreSource.contains("selectionAttachments = []")
            && workspaceStoreSource.contains("selectionTitle: sentSelectionTitle")
            && workspaceStoreSource.contains("selectionText: sentSelectionText"), "sending captures selected text attachments for the request and clears the composer attachments afterward")
        expect(workspaceStoreSource.contains("private static func boundedSelectionText")
            && workspaceStoreSource.contains("let cleaned = MarkdownSelectionSanitizer.clean(text)")
            && workspaceStoreSource.contains("Self.boundedSelectionText(cleaned)")
            && workspaceStoreSource.contains("lastIndex(where:")
            && !workspaceStoreSource.contains("String(cleaned.prefix(2_000))"), "selection context cleans callout control markers and truncates at a word or line boundary")
        expect(workspaceStoreSource.contains("var hasPrimaryConversationPaneVisible: Bool")
            && workspaceStoreSource.contains("case .documentAgentNotes, .documentNotesAgent, .documentNotesSplit:\n            return showAgent")
            && workspaceStoreSource.contains("case .immersiveConversation:\n            return true")
            && workspaceStoreSource.contains("var isConversationSurfaceVisible: Bool")
            && workspaceStoreSource.contains("var canShowSelectionPromptSurface: Bool")
            && workspaceStoreSource.contains("var canShowSelectionPromptSurface: Bool {\n        true")
            && workspaceStoreSource.contains("case .immersiveReading, .immersiveWriting:")
            && workspaceStoreSource.contains("// Overlay chat surfaces"), "workspace has one shared rule for primary conversation panes, formal conversation surfaces, and prompt-only selection affordances")
        if let updateSelectionStart = workspaceStoreSource.range(of: "func updateSelection(_ text: String")?.lowerBound,
           let removeSelectionStart = workspaceStoreSource.range(of: "func removeSelectionAttachment")?.lowerBound {
            let updateSelectionSource = String(workspaceStoreSource[updateSelectionStart..<removeSelectionStart])
            expect(updateSelectionSource.contains("let shouldRevealSelectionPrompt = anchor != nil || pinnedFloatingAgent")
                && !updateSelectionSource.contains("&& !isConversationSurfaceVisible")
                && updateSelectionSource.contains("selectionAnchor = anchor")
                && updateSelectionSource.contains("cancelPendingSelectionAttachment()")
                && !updateSelectionSource.contains("scheduleSelectionAttachment(nextSelection")
                && !updateSelectionSource.contains("let shouldRouteToConversation")
                && !updateSelectionSource.contains("addSelectionAttachment(nextSelection)")
                && !updateSelectionSource.contains("focusedPane = .agent\n                focusRequest += 1")
                && updateSelectionSource.contains("if shouldRevealSelectionPrompt {"), "selection updates show the local selection capsule in multi-pane and immersive without auto-adding chat attachments")
        } else {
            expect(false, "updateSelection source is readable")
        }
        expect(workspaceStoreSource.contains("func askSelection()")
            && workspaceStoreSource.contains("agentSurface = .selectionFloat")
            && workspaceStoreSource.contains("keepFloatingSelectionForAnswer = true")
            && workspaceStoreSource.contains("beginOrReuseSelectionAskThread")
            && workspaceStoreSource.contains("func routeSelectionToConversation")
            && workspaceStoreSource.components(separatedBy: "withAnimation(WeiBeiMotion.panel) {").count >= 3, "asking a selection keeps the floating agent open for dual-surface answers")
        if let askSelectionStart = workspaceStoreSource.range(of: "func askSelection()")?.lowerBound,
           let routeSelectionStart = workspaceStoreSource.range(of: "func routeSelectionToConversation")?.lowerBound {
            let askSelectionSource = String(workspaceStoreSource[askSelectionStart..<routeSelectionStart])
            expect(askSelectionSource.contains("addSelectionAttachment(selectionContext)")
                && askSelectionSource.contains("keepFloatingSelectionForAnswer = true")
                && askSelectionSource.contains("beginOrReuseSelectionAskThread")
                && askSelectionSource.contains("activeSelectionAskThreadID")
                && askSelectionSource.contains("if isConversationSurfaceVisible")
                && askSelectionSource.contains("keepFloatingSelectionForAnswer = false")
                && !askSelectionSource.contains("pinnedFloatingAgent = true")
                && !askSelectionSource.contains("请解释当前已选文本片段")
                && !askSelectionSource.contains("agentDraft = prompt")
                && !askSelectionSource.contains("选区："), "selection question attaches context; float opens only when conversation pane is closed")
        } else {
            expect(false, "askSelection source is readable")
        }
        expect(workspaceStoreSource.contains("selectionAttachments\n                .map { quotedReferenceBlock(text: $0.text, sourceTitle: $0.ownerTitle) }")
            && workspaceStoreSource.contains("sourceTitle: selectionContext.ownerTitle")
            && workspaceStoreSource.contains("来源：\\(currentSourceReferenceTitle)")
            && workspaceStoreSource.contains("\\(itemTitle)，章节标识：\\(locationID)，章节：\\(locationTitle)")
            && workspaceStoreSource.contains("\\(itemTitle)，章节序号：\\(sectionOrdinal)，章节：\\(locationTitle)"), "copy reference uses attached selections or a canonical file-plus-location source")
        expect(workspaceStoreSource.contains("private func quotedReferenceBlock")
            && workspaceStoreSource.contains("let quoted = MarkdownSelectionSanitizer.clean(text)")
            && workspaceStoreSource.contains("> [!quote] 选区摘录")
            && workspaceStoreSource.contains("> [!quote] Selection excerpt")
            && workspaceStoreSource.contains("\\(quoted)")
            && workspaceStoreSource.contains("> 来源：\\(sourceTitle)")
            && workspaceStoreSource.contains("> Source: \\(sourceTitle)")
            && !workspaceStoreSource.contains("## 选区摘录"), "selection excerpts use the shared quote callout format with a separate editable body")
        expect(workspaceStoreSource.contains("selectionOwnerTitle(for source: SelectionSource)") && workspaceStoreSource.contains("activeNoteItem?.isNotebookNote == true"), "selection fallback title treats notebook notes as notes")
        expect(workspaceStoreSource.contains("var selectedMaterialItem") && workspaceStoreSource.contains("!item.isNotebookNote"), "selected material excludes notebook notes")
        expect(workspaceStoreSource.contains("var navigableItems") && workspaceStoreSource.contains("let materialItems = allItems.filter { !$0.isNotebookNote }"), "material navigation skips notebook notes")
        expect(
            workspaceStoreSource.contains("guard hasSelectedMaterial else")
                && workspaceStoreSource.contains("clearReaderSearchIfNeeded()")
                && workspaceStoreSource.contains("if layout == .immersiveConversation || layout == .immersiveWriting")
                && workspaceStoreSource.contains("setLayout(.immersiveReading)"),
            "reader search reveal refuses notebook-only context and moves to a visible reader layout"
        )
        expect(
            workspaceStoreSource.contains("clearReaderSearchIfNeeded()")
                && workspaceStoreSource.contains("guard !hasSelectedMaterial else { return }")
                && workspaceStoreSource.contains("showReaderSearch = false")
                && workspaceStoreSource.contains("readerSearch = \"\""),
            "material search state clears when selection no longer points to a material"
        )
        if let hideReaderSearchStart = workspaceStoreSource.range(of: "func hideReaderSearch()")?.lowerBound,
           let updateReaderLocationStart = workspaceStoreSource.range(of: "func updateReaderLocationTitle")?.lowerBound {
            let hideReaderSearchSource = String(workspaceStoreSource[hideReaderSearchStart..<updateReaderLocationStart])
            expect(hideReaderSearchSource.contains("clearUnpinnedFloatingSelection(keepContext: false)") && !hideReaderSearchSource.contains("selectionContext = nil"), "reader search dismissal preserves pinned selection agents through the shared clear helper")
        } else {
            expect(false, "reader search dismissal source is readable")
        }
        expect(workspaceStoreSource.contains("var selectedMaterialTitle") && workspaceStoreSource.contains("selectedMaterialItem.map(displayTitle) ?? ui(\"未选择材料\""), "agent material title does not invent a current material")
        expect(workspaceStoreSource.contains("var agentMessageSourceTitle: String?") && workspaceStoreSource.contains("hasSelectedMaterial ? currentSourceReferenceTitle : activeNoteItem.map(displayTitle)") && !workspaceStoreSource.contains("source: selectedMaterialItem?.title"), "agent message source uses the canonical file location and falls back to the localized active note title")
        expect(workspaceStoreSource.contains("let sentMaterialTitle = currentSourceReferenceTitle")
            && workspaceStoreSource.contains("materialTitle: sentMaterialTitle"), "agent prompt snapshots the canonical file location so PDF pages and HTML sections reach the model")
        expect(workspaceStoreSource.contains("private var quietInsightReferenceTitle: String")
            && workspaceStoreSource.contains("selectionContext?.ownerTitle")
            && workspaceStoreSource.contains("currentSourceReferenceTitle")
            && workspaceStoreSource.contains("Quiet insight generation disabled for 1.0"), "quiet insight reference title remains available while generation stays disabled for 1.0")
        expect(workspaceStoreSource.contains("private func clearUnpinnedFloatingSelection(keepContext: Bool = true, invalidatesAgentContext: Bool = true)")
            && workspaceStoreSource.contains("if invalidatesAgentContext, selectionContext != nil")
            && workspaceStoreSource.contains("selectionContext = nil")
            && workspaceStoreSource.contains("selectionAnchor = nil")
            && workspaceStoreSource.contains("floatingSelectionPrompt = ui(\"当前选区\"")
            && workspaceStoreSource.contains("pinnedFloatingAgent = false")
            && workspaceStoreSource.contains("if agentSurface == .selectionFloat {\n                agentSurface = .hidden\n            }\n            return")
            && workspaceStoreSource.contains("guard !pinnedFloatingAgent else { return }")
            && workspaceStoreSource.contains("if agentSurface == .selectionFloat"), "cleared selections remove stale context badges before preserving any pinned floating window")
        if let dismissFloatingStart = workspaceStoreSource.range(of: "func dismissFloatingSelectionAgent()")?.lowerBound,
           let setNoteRenderModeStart = workspaceStoreSource.range(of: "func setNoteRenderMode")?.lowerBound {
            let dismissFloatingSource = String(workspaceStoreSource[dismissFloatingStart..<setNoteRenderModeStart])
            expect(!dismissFloatingSource.contains("agentDraft = \"\""), "dismissing the selection float does not erase text already typed in the shared agent composer")
        } else {
            expect(false, "floating selection dismissal source is readable")
        }
        expect(workspaceStoreSource.contains("guard Self.hasMeaningfulSelectionCharacter(cleaned) else {")
            && workspaceStoreSource.contains("now.timeIntervalSince($0) > selectionAttachmentMergeWindow")
            && workspaceStoreSource.contains("clearUnpinnedFloatingSelection(keepContext: false)\n            return\n        }")
            && workspaceStoreSource.contains("private static func hasMeaningfulSelectionCharacter(_ text: String) -> Bool")
            && workspaceStoreSource.contains("!CharacterSet.whitespacesAndNewlines.contains(scalar)")
            && workspaceStoreSource.contains("!CharacterSet.punctuationCharacters.contains(scalar)")
            && workspaceStoreSource.contains("!CharacterSet.controlCharacters.contains(scalar)"), "empty, whitespace, punctuation, or control-only selections clear the prompt without breaking a live drag-selection gesture")
        if let updateSelectionStart = workspaceStoreSource.range(of: "func updateSelection(_ text: String")?.lowerBound,
           let removeSelectionStart = workspaceStoreSource.range(of: "func removeSelectionAttachment")?.lowerBound {
            let liveSelectionUpdateSource = String(workspaceStoreSource[updateSelectionStart..<removeSelectionStart])
            expect(liveSelectionUpdateSource.contains("floatingSelectionPrompt = nextSelection.label(language: interfaceLanguage)")
                && liveSelectionUpdateSource.contains("if pinnedFloatingAgent || keepFloatingSelectionForAnswer")
                && !liveSelectionUpdateSource.contains("pinnedFloatingAgent = false")
                && liveSelectionUpdateSource.contains("cancelPendingSelectionAttachment()")
                && liveSelectionUpdateSource.contains("if shouldRevealSelectionPrompt {")
                && liveSelectionUpdateSource.contains("anchorsApproximatelyEqual")
                && !liveSelectionUpdateSource.contains("withAnimation(WeiBeiMotion.panel) {\n            selectionContext = nextSelection")
                && !liveSelectionUpdateSource.contains("withAnimation(WeiBeiMotion.panel) {\n            selectionContext = nextSelection\n            selectionAnchor = anchor"), "pinned/answer-locked floats survive new selections; continuous selection fields update without a panel spring, and only surface show/hide may animate")
        } else {
            expect(false, "updateSelection animation policy source is readable")
        }
        expect(workspaceStoreSource.contains("let itemChanged = selectedItemID != itemID") && workspaceStoreSource.contains("clearUnpinnedFloatingSelection(keepContext: false)"), "selecting a different item clears the old selection context")
        expect(workspaceStoreSource.contains("func toggleLibrary()")
            && workspaceStoreSource.contains("let willShow = !showLibrary")
            && workspaceStoreSource.contains("showLibrary = willShow")
            && workspaceStoreSource.contains("final class LibraryDrawerState: ObservableObject")
            && workspaceStoreSource.contains("let libraryDrawer = LibraryDrawerState()")
            && workspaceStoreSource.contains("DispatchQueue.main.async")
            && workspaceStoreSource.contains("clearUnpinnedFloatingSelection()")
            && !workspaceStoreSource.contains("func toggleLibrary() {\n        recordNavigationPoint()")
            && workspaceStoreSource.contains("func toggleRightPane() {\n        guard layout.hasCollapsibleRightPane else { return }\n        recordNavigationPoint()\n        showRightPane.toggle()\n        clearUnpinnedFloatingSelection()"), "the transient course drawer stays out of navigation history while durable pane visibility still records navigation")
        expect(workspaceStoreSource.contains("collapseSelectionFloatIntoConversationIfVisible()\n        focusedPane = pane")
            && workspaceStoreSource.contains("private func collapseSelectionFloatIntoConversationIfVisible()")
            && workspaceStoreSource.contains("guard isConversationSurfaceVisible, agentSurface == .selectionFloat else { return }")
            && workspaceStoreSource.contains("selectionAnchor = nil\n        pinnedFloatingAgent = false"), "opening or focusing the formal conversation surface collapses any stale selection mini window but keeps the selected text context")
        expect(workspaceStoreSource.contains("focus(showRightPane ? rightPaneRevealFocus : fallbackDocumentPaneFocus())")
            && workspaceStoreSource.contains("private var rightPaneRevealFocus: PaneFocus")
            && workspaceStoreSource.contains("if layout.isDocumentThreePane")
            && workspaceStoreSource.contains("return normalizedThreePaneOrder.last?.focus ?? .notes")
            && workspaceStoreSource.contains("case .documentNotesAgent, .immersiveConversation:\n            return .agent"), "right-pane reveal focuses the visible pane by current role order instead of legacy fixed layout names")
        expect(workspaceStoreSource.contains("func revealLibrary()")
            && workspaceStoreSource.contains("if !showLibrary {\n            clearUnpinnedFloatingSelection()\n        }")
            && workspaceStoreSource.contains("showLibrary = true\n        focus(.library)")
            && !workspaceStoreSource.contains("focus(.library)\n        save()"), "library reveal uses transient in-memory state without writing the workspace")
        expect(workspaceStoreSource.contains("layout == .immersiveReading || layout == .immersiveWriting")
            && workspaceStoreSource.contains("layout = .immersiveConversation")
            && !workspaceStoreSource.contains("agentSurface = .cornerPanel")
            && !workspaceStoreSource.contains("agentSurface = .bottomDrawer"), "agent focus in immersive layouts opens immersive conversation instead of deleted overlays")
        if let setLayoutStart = workspaceStoreSource.range(of: "func setLayout(_ layout: WorkspaceLayout)")?.lowerBound,
           let setAgentSurfaceStart = workspaceStoreSource.range(of: "func setAgentSurface")?.lowerBound {
            let setLayoutSource = String(workspaceStoreSource[setLayoutStart..<setAgentSurfaceStart])
            expect(!setLayoutSource.contains("showLibrary = false"), "layout switching preserves the current library visibility")
            expect(!setLayoutSource.contains("showRightPane = true"), "layout switching preserves a user-collapsed auxiliary pane")
            expect(setLayoutSource.contains("clearUnpinnedFloatingSelection()"), "layout switching invalidates stale floating selection anchors")
        } else {
            expect(false, "layout switching source is readable")
        }
        if let agentFocusStart = workspaceStoreSource.range(of: "if pane == .agent")?.lowerBound,
           let focusEnd = workspaceStoreSource.range(of: "focusedPane = pane")?.lowerBound {
            let agentFocusSource = String(workspaceStoreSource[agentFocusStart..<focusEnd])
            expect(!agentFocusSource.contains("showLibrary = false"), "agent focus does not close a user-opened immersive library")
        } else {
            expect(false, "agent focus source is readable")
        }
        if let insertStart = workspaceStoreSource.range(of: "func insertMarkdownSnippet")?.lowerBound,
           let insertEnd = workspaceStoreSource[insertStart...].range(of: "\n    }\n")?.upperBound {
            let insertSource = String(workspaceStoreSource[insertStart..<insertEnd])
            expect(!insertSource.contains("showLibrary = false"), "markdown insertion keeps a user-opened immersive library visible")
        } else {
            expect(false, "markdown insertion source is readable")
        }
        if let setNoteModeStart = workspaceStoreSource.range(of: "func setNoteRenderMode(_ mode: NoteRenderMode)")?.lowerBound,
           let revealStart = workspaceStoreSource.range(of: "private func revealRichWritingSurface")?.lowerBound {
            let setNoteModeSource = String(workspaceStoreSource[setNoteModeStart..<revealStart])
            expect(
                setNoteModeSource.contains("let nextMode = mode.visibleMode")
                    && setNoteModeSource.contains("layout = .immersiveWriting")
                    && setNoteModeSource.contains("showNotes = true")
                    && setNoteModeSource.contains("noteRenderMode = nextMode")
                    && setNoteModeSource.contains("focus(.notes)"),
                "note render mode commands normalize legacy preview, reveal, and focus the writing surface"
            )
        } else {
            expect(false, "note render mode source is readable")
        }
        expect(workspaceStoreSource.contains("var canUseSelectionAgentSurface: Bool")
            && workspaceStoreSource.contains("var visibleAgentSurfaces: [AgentSurface]")
            && workspaceStoreSource.contains("guard surface != .selectionFloat || canUseSelectionAgentSurface else { return }")
            && workspaceStoreSource.contains("case .selectionPrompt:")
            && workspaceStoreSource.contains("guard canUseSelectionAgentSurface else { return false }")
            && workspaceStoreSource.contains("setAgentSurface(.selectionFloat)")
            && workspaceStoreSource.contains("self.agentSurface = agentSurface == .selectionFloat ? .hidden : agentSurface")
            && workspaceStoreSource.contains("agentSurface: agentSurface == .selectionFloat ? .hidden : agentSurface"), "selection-float agent surface is hidden, rejected, and never restored as durable workspace chrome")
        expect(!workspaceStoreSource.contains("selectedItem?.title ?? \"当前材料\"")
            && !workspaceStoreSource.contains("保存后 Agent 会用")
            && !workspaceStoreSource.contains("Agent 可在打包应用里直接读取")
            && !workspaceStoreSource.contains("Agent 不会编造回答")
            && workspaceStoreSource.contains("AgentFailureKind.classify(error)")
            && workspaceStoreSource.contains("draftPreserved: true")
            && workspaceStoreSource.contains("func retryLastFailedAgentRequest()")
            && !workspaceStoreSource.contains("Agent 设置")
            && workspaceStoreSource.contains("PI 与在线密钥均不可用，当前使用离线草稿。")
            && workspaceStoreSource.contains("OfflineStudyAgentRuntime().respond")
            && workspaceStoreSource.contains("PiAgentRuntime")
            && workspaceStoreSource.contains("appendAgentMessage(AgentMessage(role: .user, text: question, source: sourceTitle))")
            && !workspaceStoreSource.contains("未配置 OPENAI_API_KEY 或钥匙串密钥")
            // Provider-aware key help + in-field key used for requests (local secret file + keychain mirror).
            && workspaceStoreSource.contains("正在使用本机环境变量")
            && workspaceStoreSource.contains("设置中的密钥")
            && workspaceStoreSource.contains("密钥保存在魏碑应用数据中")
            && workspaceStoreSource.contains("let fieldKey = OpenAIAPIKeyStore.cleaned(openAIAPIKey)")
            && workspaceStoreSource.contains("resolveStoredAPIKey()")
            && workspaceStoreSource.contains("已清除密钥。")
            && workspaceStoreSource.contains("密钥已保存到当前配置。")
            && workspaceStoreSource.contains("AgentCredentialProfileStore")
            && !workspaceStoreSource.contains("打包应用可直接读取")
            && !workspaceStoreSource.contains("已清除钥匙串密钥。")
            && !workspaceStoreSource.contains("已保存到 macOS 钥匙串。")
            && !workspaceStoreSource.contains("已选择材料、当前选区和右侧笔记"), "agent context and setup notices avoid fake material fallback copy and visible internal agent labels")
        expect(
            workspaceStoreSource.contains("let selectedProvider = agentProviderID")
                && workspaceStoreSource.contains("let linkedOAuth = PiOAuthService.readLinkedOAuthProviders")
                && workspaceStoreSource.contains("if !explicitProvider.isEmpty { return explicitProvider }")
                && workspaceStoreSource.contains("if selectedProvider == .openaiCodex { return \"openai-codex\" }")
                && workspaceStoreSource.contains("apiKey: usesOAuth ? nil : credential?.key")
                && workspaceStoreSource.contains("thinkingLevel: thinking.isEmpty ? \"medium\" : thinking"),
            "PI honors the selected provider, reuses subscription OAuth without injecting an API key, and keeps the current thinking default"
        )
        if let requestStart = workspaceStoreSource.range(of: "private func performAgentRequest() async")?.lowerBound,
           let executionStart = workspaceStoreSource.range(of: "private func executeStudyAgentRequest")?.lowerBound {
            let requestSource = String(workspaceStoreSource[requestStart..<executionStart])
            expect(requestSource.contains("agentDraft = \"\"")
                && requestSource.contains("flushStagedNoteDraftForAgentContext()")
                && requestSource.contains("selectionAttachments = []")
                && requestSource.contains("let shouldClearSentDocumentSelection = sentSelectionText != nil && selectionContext?.source == .document")
                && requestSource.contains("clearUnpinnedFloatingSelection(keepContext: false, invalidatesAgentContext: false)")
                && requestSource.contains("appendAgentMessage(AgentMessage(role: .user, text: question, source: sourceTitle))")
                && requestSource.contains("let sentLearningContext = makeLearningContext()")
                && requestSource.contains("let courseBuild = try await makeCourseContext(query: courseQuery)")
                && requestSource.contains("materialIsTruncated: courseBuild.selectedMaterialIsTruncated")
                && requestSource.contains("courseContext: courseBuild.context")
                && requestSource.contains("learningContext: sentLearningContext")
                && requestSource.contains("let reply = try await executeStudyAgentRequest(request)")
                && requestSource.contains("applyLearningUpdate(")
                && requestSource.contains("expectedUserQuestion: request.question")
                && requestSource.contains("requestWorkspaceRevision == agentContextRevision")
                && requestSource.contains("requestMemoryRevision == learningMemoryRevision")
                && requestSource.contains("lastAgentReplyContextRevision = requestWorkspaceRevision")
                && requestSource.contains("contextRevision: \"\\(requestWorkspaceRevision):\\(requestID.uuidString.lowercased())\""),
                "agent send clears the composer, executes the unified runtime, and accepts only the current context revision")
        } else {
            expect(false, "unified agent request source is readable")
        }
        expect(workspaceStoreSource.contains("@Published private(set) var studySessions")
            && workspaceStoreSource.contains("func createStudySession()")
            && workspaceStoreSource.contains("func activateStudySession(_ id: UUID)")
            && workspaceStoreSource.contains("private func syncActiveStudySession(titleSeed: String? = nil)")
            && workspaceStoreSource.contains("private func appendAgentMessage(_ message: AgentMessage)"), "agent conversations are durable course study sessions")
        expect(workspaceStoreSource.contains("noteSourceLinks: noteSourceLinks")
            && workspaceStoreSource.contains("studyLocationsByItemID: studyLocationsByItemID")
            && workspaceStoreSource.contains("learningMemoryEntries: learningMemoryEntries")
            && workspaceStoreSource.contains("learningMemoryRevision: learningMemoryRevision")
            && workspaceStoreSource.contains("studySessions: studySessions")
            && workspaceStoreSource.contains("activeStudySessionID: activeStudySessionID"), "course links, progress, memory, and sessions are saved with the workspace")
        expect(workspaceStoreSource.contains("acceptedUpdate.resolutions = update.resolutions.prefix(12).filter")
            && workspaceStoreSource.contains("func confirmLearningMemoryResolution")
            && workspaceStoreSource.contains("private static func resolutionEvidenceMatches")
            && workspaceStoreSource.contains("StudyAgentResolutionEvidence.matches")
            && workspaceStoreSource.contains("func restoreLearningMemory(")
            && workspaceStoreSource.contains("resolutionEvidence = \"[用户：界面确认]\"")
            && notesAgentSource.contains("建议结案：")
            && notesAgentSource.contains("store.confirmLearningMemoryResolution(resolution)")
            && notesAgentSource.contains("store.restoreLearningMemoryResolution(resolution)"), "PI can only propose memory resolution; user confirmation persists it and the UI can undo it")
        expect(workspaceStoreSource.contains("} else {\n            restoreCurrentStudyLocation()\n            recordCurrentStudyLocation(incrementVisit: false)\n        }")
            && workspaceStoreSource.contains("private func restoreCurrentStudyLocation()")
            && workspaceStoreSource.contains("readerPageIndex = max(location.pageIndex ?? 0, 0)")
            && workspaceStoreSource.contains("requestReaderPDFPage(location.pageIndex, recordsLocation: false)"), "saved heading and PDF page are restored before startup records the current study location")
        expect(workspaceStoreSource.contains("private func makeCourseContext(query: String) async throws")
            && workspaceStoreSource.contains("CourseKnowledgeIndex.build(")
            && workspaceStoreSource.contains("courseDocumentSearchIndex: CourseDocumentSearchIndex")
            && workspaceStoreSource.contains("course-search-v3.sqlite3")
            && workspaceStoreSource.contains("removeLegacyCourseIndex")
            && workspaceStoreSource.contains("let indexedByItemID = searchIndex.lookup(")
            && workspaceStoreSource.contains("candidate.item.isSample")
            && workspaceStoreSource.contains("Task.detached(priority: .userInitiated)")
            && workspaceStoreSource.contains("withTaskCancellationHandler")
            && workspaceStoreSource.contains("migrateNoteSourceLinksFromMarkdown()"), "agent queries the persistent course index in the background and migrates durable note-source links")
        if let selectStart = workspaceStoreSource.range(of: "func select(itemID: String?)")?.lowerBound,
           let selectEnd = workspaceStoreSource[selectStart...].range(of: "\n    func ", options: [], range: workspaceStoreSource.index(after: selectStart)..<workspaceStoreSource.endIndex)?.lowerBound {
            let selectSource = String(workspaceStoreSource[selectStart..<selectEnd])
            expect(!selectSource.contains("messages = []")
                && selectSource.contains("syncActiveStudySession()")
                && selectSource.contains("recordCurrentStudyLocation("), "changing course material preserves the active conversation and records progress")
        } else {
            expect(false, "course material selection source is readable")
        }
        expect(workspaceStoreSource.contains("func stageNoteDraft(_ value: String, for itemID: String?)")
            && workspaceStoreSource.contains("if stagedNoteDraft?.itemID != itemID || stagedNoteDraft?.value != value {\n            invalidateAgentContext()")
            && workspaceStoreSource.contains("private func flushStagedNoteDraftForAgentContext()")
            && notesAgentSource.contains("store.stageNoteDraft(value, for: draftNoteItemID)"), "agent requests flush the current local note-editor draft before snapshotting context")
        expect(workspaceStoreSource.contains("func updateReaderLocationTitle(_ title: String?)")
            && workspaceStoreSource.contains("func updateReaderHTMLLocation(id: String?, title: String?, reason: String)")
            && workspaceStoreSource.contains("PaneToggleContinuityVerifier.recordHTMLLocationCall(reason: reason)")
            && workspaceStoreSource.contains("if !incrementVisit,")
            && workspaceStoreSource.contains("previous?.locationID == locationID")
            && workspaceStoreSource.contains("private(set) var studyLocationsByItemID")
            && !workspaceStoreSource.contains("@Published private(set) var studyLocationsByItemID")
            && readerViewSource.contains("guard change.reason == .scroll || change.reason == .jump else { return }")
            && readerViewSource.contains("Task.sleep(nanoseconds: 350_000_000)"), "passive reader layout stays local while settled user navigation persists without publishing duplicate study locations")
        expect(workspaceStoreSource.contains("var agentPromptScope") && workspaceStoreSource.contains("var selectionPromptScope") && !workspaceStoreSource.contains("var libraryOrganizationScope"), "agent prompt builders avoid half-built library organization context")
        expect(!workspaceStoreSource.contains("请根据当前文档和当前笔记") && !workspaceStoreSource.contains("请根据当前材料和当前笔记") && !workspaceStoreSource.contains("结合当前文档和笔记"), "agent draft presets do not hardcode fake material context")
        expect(workspaceStoreSource.contains("正在静默阅读当前材料和笔记。")
            && workspaceStoreSource.contains("正在静默阅读当前笔记。")
            && !workspaceStoreSource.contains("Agent 正在静默阅读"), "quiet insight progress copy avoids a visible internal agent label")
        expect(workspaceStoreSource.contains("scenario == \"notebook-creation-flow\"")
            && workspaceStoreSource.contains("promptCreateBlankNotebookNote()\n            return"), "visual verification can exercise blank notebook creation")
        expect(workspaceStoreSource.contains("private func noteBlockForAgentAnswer")
            && workspaceStoreSource.contains("AgentOfflinePreview.suggestedNoteBlock(from: text, language: interfaceLanguage)")
            && workspaceStoreSource.contains("guard !text.hasPrefix(\"#\") else { return text }")
            && workspaceStoreSource.contains("return \"## \\(ui(\"整理建议\", \"Organization suggestion\"))\\n\\(text)\"")
            && workspaceStoreSource.contains("let content = latestAgentNoteProposal?.markdown ?? answer.text")
            && workspaceStoreSource.contains("markdown: \"\\n\\(noteBlockForAgentAnswer(content))\"")
            && !workspaceStoreSource.contains("## Agent 整理建议"), "agent note writeback prefers a revision-matched PI proposal before falling back to a reader-facing answer section")
        expect(workspaceStoreSource.contains("func createBlankNotebookNote()")
            && workspaceStoreSource.contains("func createNotebookNoteFromCurrentMaterial()")
            && workspaceStoreSource.contains("func promptCreateBlankNotebookNote()")
            && workspaceStoreSource.contains("func promptCreateNotebookNoteFromCurrentMaterial()")
            && workspaceStoreSource.contains("@Published var notebookCreationDraft")
            && workspaceStoreSource.contains("struct NotebookCreationDraft")
            && workspaceStoreSource.contains("private func createNotebookNote(seed: NotebookNoteSeed, title")
            && !workspaceStoreSource.contains("func resetNote()")
            && !workspaceStoreSource.contains("updateNote(defaultNote(for: selectedItem))"), "new note commands separate blank notes from current-material notes and route through the inline naming strip")
        expect(workspaceStoreSource.contains("private func openExistingNotebookNote(for material: StudyItem) -> Bool")
            && workspaceStoreSource.contains("if openExistingNotebookNote(for: selectedMaterialItem)")
            && workspaceStoreSource.contains("private func existingNotebookNote(for material: StudyItem) -> StudyItem?")
            && workspaceStoreSource.contains("let titles = Set([currentTitle, chineseTitle, englishTitle, displayChineseTitle, displayEnglishTitle])")
            && workspaceStoreSource.contains("已打开现有资料笔记"), "current-material note creation opens an existing matching notebook note instead of prompting a duplicate")
        expect(workspaceStoreSource.contains("case currentMaterial(StudyItem)")
            && workspaceStoreSource.contains("private func suggestedNotebookTitle(for seed: NotebookNoteSeed)")
            && workspaceStoreSource.contains("let markdown = defaultNotebookNote(title: item.title, sourceItem: sourceItem)")
            && workspaceStoreSource.contains("try markdown.write(to: url"), "new notebook notes are backed by local markdown files and can be seeded from the current material")
        expect(workspaceStoreSource.contains("func cancelNotebookNoteCreation()")
            && workspaceStoreSource.contains("func confirmNotebookNoteCreation()")
            && workspaceStoreSource.contains("notebookCreationDraft = NotebookCreationDraft(")
            && workspaceStoreSource.contains("let title = draft.title.trimmingCharacters")
            && workspaceStoreSource.contains("func select(itemID: String?)")
            && workspaceStoreSource.contains("private func selectMeasured(itemID: String?) {\n        invalidateAgentContext()\n        persistCurrentNote()\n        notebookCreationDraft = nil")
            && !workspaceStoreSource.contains("private func promptCreateNotebookNote(seed: NotebookNoteSeed)")
            && !workspaceStoreSource.contains("alert.messageText = seed.isBlank"), "new-note creation opens the inline naming strip and confirms through the shared local markdown creator")
        expect(workspaceStoreSource.contains("importedItems.append(item)")
            && workspaceStoreSource.contains("courseDocumentSearchIndex.synchronize(allItems)")
            && workspaceStoreSource.contains("addNoteSourceLink(noteItemID: item.id, sourceItemID: sourceItem.id)")
            && workspaceStoreSource.contains("activeNotebookItemID = item.id\n            noteText = markdown\n            revealRichWritingSurface()\n            focus(.notes)\n            save()"), "new notebook notes persist their material link, join the course index, and open in the note pane without replacing the reader material")
        expect(workspaceStoreSource.contains("private func showTransientNoteStatus(_ message: String)")
            && workspaceStoreSource.contains("transientNoteStatus = message")
            && workspaceStoreSource.contains("@Published var transientNoteStatus")
            && workspaceStoreSource.contains("Task { @MainActor [weak self] in")
            && workspaceStoreSource.contains("if self.transientNoteStatus == token")
            && workspaceStoreSource.contains("已新建空白笔记")
            && workspaceStoreSource.contains("已为当前资料新建笔记"), "successful note creation feedback clears itself and names the creation path")
        expect(workspaceStoreSource.contains("func promptRenameNotebookNote(itemID: String)")
            && workspaceStoreSource.contains("@Published var notebookRenameDraft")
            && workspaceStoreSource.contains("struct NotebookRenameDraft")
            && workspaceStoreSource.contains("func cancelRenameNotebookNote()")
            && workspaceStoreSource.contains("func confirmRenameNotebookNote()")
            && workspaceStoreSource.contains("func renameNotebookNote(itemID: String, to rawTitle: String)")
            && workspaceStoreSource.contains("sourceMarkdown = wasActiveNotebook ? noteText : try notebookMarkdownReader(oldURL)")
            && workspaceStoreSource.contains("try writePendingNotebookRenameJournal(renameJournal)")
            && workspaceStoreSource.contains("try notebookFileMover(oldURL, newURL)")
            && workspaceStoreSource.contains("let coordinator = NSFileCoordinator(filePresenter: nil)")
            && workspaceStoreSource.contains("try notebookMarkdownWriter(retitledMarkdown, coordinatedURL)")
            && workspaceStoreSource.contains("outputDigest == expectedOutputDigest")
            && workspaceStoreSource.contains("activeNotebookItemID = newID")
            && workspaceStoreSource.contains("noteText = retitledMarkdown")
            && workspaceStoreSource.contains("replaceNavigationItemID(oldID, with: newID)")
            && workspaceStoreSource.contains("guard save() else")
            && workspaceStoreSource.contains("文件已重命名，但课程状态尚未写入磁盘")
            && workspaceStoreSource.contains("notebookRenameDraft = nil")
            && !workspaceStoreSource.contains("alert.messageText = ui(\"重命名笔记\""), "renaming a notebook note updates the local markdown file, active note identity, heading, and navigation snapshots without a system alert")
        expect(workspaceStoreSource.contains("let title = item.map(displayTitle) ?? ui(\"新笔记\"")
            && workspaceStoreSource.contains("let sourceItem = item?.isNotebookNote == true ? nil : item")
            && workspaceStoreSource.contains("private func defaultNotebookNote(title: String, sourceItem: StudyItem?)")
            && workspaceStoreSource.contains("let excerptSeed = sourceItem.map { ui(\"> 来源：\\(displayTitle(for: $0))\\n\"")
            && workspaceStoreSource.contains("## \\(ui(\"核心要点\", \"Key Points\"))")
            && workspaceStoreSource.contains("## \\(ui(\"待追问\", \"Follow-up Questions\"))")
            && !workspaceStoreSource.contains("## 核心要点\n        - ")
            && !workspaceStoreSource.contains("## 待追问\n        - ")
            && !workspaceStoreSource.contains("未命名材料"), "new note templates avoid fake source copy and empty bullets")
        expect(workspaceStoreSource.contains("return cleanLegacyPlaceholder(notesByItemID[item.id] ?? defaultNote(for: item))")
            && workspaceStoreSource.contains("guard let markdown = String(data: data, encoding: .utf8)")
            && workspaceStoreSource.contains("noteBackingContentDigestsByItemID[item.id] = Self.noteContentDigest(data)")
            && workspaceStoreSource.contains("return cleanLegacyPlaceholder(markdown)")
            && workspaceStoreSource.contains("静默洞察|Agent 洞察")
            && workspaceStoreSource.contains("with: \"> [!note] 阅读线索\\n>\\n> $1\\n>\\n> 来源：$2\"")
            && workspaceStoreSource.contains(#"(?m)^> \[!note\] 阅读线索\n> ([^\n])"#)
            && workspaceStoreSource.contains(#"(?m)^> \[!quote\]([^\n]*)\n> ([^\n])"#)
            && workspaceStoreSource.contains(".replacingOccurrences(of: \"\\n* <br />\\n\", with: \"\\n\")")
            && workspaceStoreSource.contains(".replacingOccurrences(of: \"\\n- <br />\\n\", with: \"\\n\")"), "note loading cleans legacy empty-list placeholders")
        expect(workspaceStoreSource.contains("已创建双链笔记：\\(url.lastPathComponent)") && !workspaceStoreSource.contains("已创建双链笔记：\\(url.path)") && !workspaceStoreSource.contains("无法创建双链笔记：\\(url.path)"), "wikilink note statuses avoid exposing full local paths")
        expect(workspaceStoreSource.contains("private func revealRichWritingSurface()")
            && workspaceStoreSource.contains("layout = .immersiveWriting")
            && workspaceStoreSource.contains("showNotes = true")
            && workspaceStoreSource.contains("noteRenderMode = .rich"), "writing actions share one rich writing surface reveal")
        expect(workspaceStoreSource.contains("func insertMarkdownSnippet(_ markdown: String) {\n        revealRichWritingSurface()")
            && workspaceStoreSource.contains("func useSelectedMarkdownAsNotebookNote()")
            && workspaceStoreSource.contains("revealRichWritingSurface()\n        focus(.notes)"), "markdown insertion and imported markdown notes reveal the rich writing surface")
        expect(!workspaceStoreSource.contains("当前页提示"), "quiet insight avoids old page alert title")
        expect(workspaceStoreSource.contains("阅读线索"), "quiet insight uses margin-note language")
        expect(appSource.contains("if store.canCopyReference") && appSource.contains("if store.hasSelectedMaterial") && appSource.contains("Button(store.ui(\"打开资料内搜索\""), "app menu hides material-only actions when there is no material context")
        expect(appSource.contains("Button(store.ui(\"新建空白笔记\"") && appSource.contains("{ animateLayout { store.promptCreateBlankNotebookNote() } }")
            && appSource.contains("Button(store.ui(\"从当前资料开笔记\"")
            && appSource.contains("animateLayout { store.promptCreateNotebookNoteFromCurrentMaterial() }"), "new-note menu commands use layout motion and expose blank/material paths separately")
        expect(appSource.contains("Button(store.sendAgentActionTitle)") && workspaceStoreSource.contains("var sendAgentActionTitle: String"), "app send command uses one stable action label")
        expect(appSource.contains("if store.isAskingAgent || !store.agentDraft.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty")
            && appSource.contains("store.isAskingAgent ? store.cancelAgentRequest() : store.askAgent()")
            && appSource.contains(".keyboardShortcut(.return, modifiers: [.command])"), "app menu hides the agent send action until a draft can really send")
        expect(appSource.contains("Button(store.showLibrary ? store.ui(\"收起课程目录\"")
            && !appSource.contains("恢复资料")
            && appSource.contains("Button(store.showRightPane ? store.ui(\"收起辅助栏\""), "app menu names pane toggles by current state")
        expect(appSource.contains("Button(store.ui(\"三栏工作台\", \"Three-Pane Workspace\"))")
            && !appSource.contains("Button(WorkspaceLayout.documentNotesAgent.label")
            && appSource.contains("Button(WorkspaceLayout.documentNotesSplit.label(language: store.interfaceLanguage))")
            && appSource.contains("Button(store.ui(\"交换笔记与对话\"")
            && appSource.contains("store.swapThreePaneSecondaryPanes()")
            && appSource.contains(".keyboardShortcut(\"s\", modifiers: [.command, .option])")
            && appSource.contains(".keyboardShortcut(\"2\", modifiers: [.command, .option])"), "app menu exposes one draggable three-pane workspace entry and gives split view the second layout shortcut")
        expect(!appSource.contains("AgentSurface.bottomDrawer")
            && !appSource.contains("AgentSurface.cornerPanel")
            && !appSource.contains("AgentSurface.quietInsight")
            && appSource.contains("Button(AgentSurface.selectionFloat.actionLabel(language: store.interfaceLanguage))")
            && appSource.contains("if store.canUseSelectionAgentSurface")
            && AgentSurface.hidden.label(language: .chinese) == "隐藏对话"
            && AgentSurface.hidden.label(language: .english) == "Hide Chat"
            && AgentSurface.hidden.actionLabel(language: .english) == "Hide Chat"
            && !appSource.contains("Agent 底部抽屉")
            && !appSource.contains("Agent 右下角小窗")
            && !appSource.contains("Agent 划线浮层")
            && !appSource.contains("Agent 静默洞察"), "app menu uses the same user-facing agent surface labels as the command palette")
        expect(appSource.contains("if store.layout.hasCollapsibleRightPane")
            && appSource.contains("if store.canApplyAgentAnswer")
            && appSource.contains("if store.canReplaceNoteSelection")
            && !appSource.contains(".disabled("), "app menu hides unavailable actions instead of showing disabled grey items")
        expect(appSource.contains("Button(store.ui(\"聚焦课程目录\"")
            && appSource.contains("{ animateLayout { store.focus(.library) } }")
            && appSource.contains("Button(store.ui(\"聚焦对话\"")
            && appSource.contains("{ animateLayout { store.focus(.agent) } }")
            && !appSource.contains("Button(\"聚焦 Agent\")")
            && appSource.contains("Button(store.ui(\"下一份资料\"")
            && appSource.contains("{ animateLayout { store.selectAdjacentItem(step: 1) } }"), "app menu focus and material navigation use the same layout motion as shortcuts")
        expect(appSource.contains("Button(store.ui(\"写入回答到笔记\"")
            && appSource.contains("{ animatePanel { store.applyLastAgentAnswerToNote() } }")
            && appSource.contains("Button(store.ui(\"替换笔记选区\"")
            && appSource.contains("{ animatePanel { store.replaceSelectionWithLastAgentAnswer() } }")
            && appSource.contains("Button(store.ui(\"追加整理建议\"")
            && appSource.contains("{ animatePanel { store.applyAgentPatchToEditor() } }")
            && !appSource.contains("用 Agent 替换笔记选区")
            && !appSource.contains("追加 Agent 整理建议"), "app menu agent write actions use the same panel motion as shortcuts")
    }
}
